### ISSUE TITLE
Apply surrogate variables learned from some tissues to another tissue

### ISSUE THREAD

**Issue by qwangmsk** [jtleek/svaseq#2]
Dear Jeff,

Sorry to bother you again. I have some RNA-seq samples from two batches. For batch 1, I have tissues A, B, and C. For batch 2, I have tissues A and B only. I want to examine expression of some genes in all the samples. I wonder if it is possible to learn surrogate variables (or batch effect) from tissues A, B (from both batches) and then apply them to tissue C to remove batch bias. If svaseq can do it, which function or procedure you would suggest to use? Thanks in advance.

Best,
Qingguo

**Comment by jtleek** [comment]
Hi Qinqguo

This is not exactly the case sva/svaseq is designed for. We have done some
work on "predicting" the batch effects in new samples, but have shown that
across known batches this can have limited effectiveness:

http://www.ncbi.nlm.nih.gov/pubmed/25332844

You would need to apply the `fsva` function to the log2(counts + 1)
transformed data, then you could try to predict the batches for tissue C.

A more direct analysis would just combine all of the batches/tissue types
and apply svaseq to remove batches.

Best

Jeff

**Comment by qwangmsk** [comment]
Hi Jeff,

Thanks for your reply. Because tissues A, B, and C are very different, if I combine all of the batches/tissue types to run svaseq, is there risk that tissue-specific signals be cancelled out? How to avoid the risk if it is the case?  

Thanks again,
Qingguo

**Comment by jtleek** [comment]
Hi Qinguo

Include the tissue variable as one of the "protected" variables in the
mod/mod0 matrices when you run sva.

Best

Jeff

**Comment by qwangmsk** [comment]
OK. I will give it a try. Thanks so much!

Qingguo
